=== VeselaStoyanova/XMLProject/Project/excursions_catalog.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT excursions_catalog (excursions)>
<!ELEMENT excursions (excursion+)>
<!ELEMENT excursion (basic_info, secondary_info, rules, excursion_more_info)>
<!ELEMENT basic_info (name, towns, country, price, type, image)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT towns (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT secondary_info (about_excursion, about_town)>
<!ELEMENT about_excursion (route, dates, nights_number)>
<!ELEMENT route (#PCDATA)>
<!ELEMENT dates (#PCDATA)>
<!ELEMENT nights_number (#PCDATA)>
<!ELEMENT about_town (landmarks, history, climate, time_zone, currency)>
<!ELEMENT landmarks (#PCDATA)>
<!ELEMENT history (#PCDATA)>
<!ELEMENT climate (#PCDATA)>
<!ELEMENT time_zone (#PCDATA)>
<!ELEMENT currency (#PCDATA)>
<!ELEMENT rules (price_include, price_not_include, necessary_documents, more_info)>
<!ELEMENT price_include (#PCDATA)>
<!ELEMENT price_not_include (#PCDATA)>
<!ELEMENT necessary_documents (#PCDATA)>
<!ELEMENT more_info (enrollment_conditions, payment_terms, penalties)>
<!ELEMENT enrollment_conditions (#PCDATA)>
<!ELEMENT payment_terms (#PCDATA)>
<!ELEMENT penalties (#PCDATA)>
<!ELEMENT excursion_more_info (program, more_excursions, images)>
<!ELEMENT program (#PCDATA)>
<!ELEMENT more_excursions (#PCDATA)>
<!ELEMENT images (image+)>

<!ATTLIST excursion excursionId CDATA #REQUIRED>
<!ATTLIST basic_info code CDATA #REQUIRED>
<!ATTLIST basic_info category (Европа|Екзотика) #REQUIRED>
<!ATTLIST type type (Самолет|Автобус) #REQUIRED>
<!ATTLIST price priceCurrency CDATA #REQUIRED>
<!ATTLIST currency countryCurrency CDATA #REQUIRED>
<!ATTLIST nights_number numberOfNights CDATA #REQUIRED>

=== VeselaStoyanova/XMLProject/valid_xml_4.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="html_transformation_1.xsl"?>
<!DOCTYPE excursions_catalog SYSTEM "excursions_catalog.dtd">
<excursions_catalog>
    <excursions>
        <excursion excursionId="EXC4">
            <basic_info code="ExcursionVeniceCarnival1" category="Европа">
                <code>ExcursionVeniceCarnival</code>
                <category>Европа</category>
                <name>Италианска класика - Милано, Верона и карнавалът във Венеция</name>
                <towns>Милано, Верона, Венеция</towns>
                <country>Италия</country>
                <price priceCurrency="лв">620</price>
                <type type="Самолет"/>
                <image>milano.jpg</image>
            </basic_info>
            <secondary_info>
                <about_excursion>
                    <route>София-Милано-Верона-Венеция-Милано-София</route>
                    <dates>13.02.2022-17.02.2022</dates>
                    <nights_number numberOfNights="3"/>
                </about_excursion>
                <about_town>
                    <landmarks>
                        къщата на Ромео и Жулиета, площада Сан Марко, замъка Сфорцеско, миланската опера Ла Скала, катедралата Дуомо ди Милано
                    </landmarks>
                    <history>
                        Историята на тази част от Италия е изключително дълга, но и много интересна. Ще можете да и се насладите, докато обикаляме из италианските улички.
                    </history>
                    <climate>
                        Времето в тази част на Италия през февруари месец е студено. Нощните температура могат да паднат 1-2 градуса под нулата, а през деня се повишават до 6-10 градуса над нулата.
                    </climate>
                    <time_zone>
                        България 12 ч. - Италия 11 ч.;
                    </time_zone>
                    <currency countryCurrency="Италия - Евро (EUR) - 1 € = 1,9558 лв;"/>
                </about_town>
            </secondary_info>
            <rules>
                <price_include>
                    Самолетен билет : София – Бергамо, Милано – София;
				    Малък ръчен багаж до 10 кг с размери 40/25/20 см;
				    Летищни такси в размер на 45 евро;
				    3 нощувки с включени закуски / 2 в района на Верона и 1 в района на Милано; 
				    Медицинската застраховка "Помощ при пътуване в чужбина" за лица до 69.99 години;
				    БОНУС Туристическа обиколка във Верона;
				    Водач от агенцията по време на цялото пътуване;
				    Безжична аудио система по време на туристическите обиколки;
				    Екскурзоводско обслужване на български език.
                </price_include>
                <price_not_include>
                    Трансфер летище - хотел- летище – 30 евро ;
					Допълнителен чекиран багаж до 10кг или до 20 кг;
					Сити такса в размер от 2 до 4 евро/нощувка/човек - заплаща се лично от туриста на рецепция;
					Медицинската застраховка "Помощ при пътуване в чужбина" за лица над 70 години;
					Двупосочен трансфер от Вашия град до сборен пункт в София;
					Туристическа такса във Венеция в размер на 3 до 10 евро. Заплаща се на място от туриста.
					Билети за градски транспорт;
					Допълнителни екскурзии и входни такси:
                </price_not_include>
                <necessary_documents>
                    лична карта и/или задграничен паспорт;
                </necessary_documents>
                <more_info>
                    <enrollment_conditions>
                        Записването е възможно по телефон, интернет или директно в офиса. Резервацията се счита за валидна след сключване на Договор и внасяне на депозит.
					    Срокът да заявите вашето пътуване е 30 дни преди датата на отпътуване.
                    </enrollment_conditions>
                    <payment_terms>
                        До 1 ден след резервацията е необходимо да бъде платено 20% от сумата. До 21 дни преди датата на отпътуване е необходимо да се плати 100% от сумата.
                    </payment_terms>
                    <penalties>
                        за промени/анулация 1 ден след плащане на депозита и/или до 30 дни преди датата на заминаване - 30%;
		                за промени/анулация между 29-тия и 18-тия ден преди датата на заминаване - 80%;
		                за промени/анулация 17 дни преди датата на заминаване - 100%;
                    </penalties>
                </more_info>
            </rules>
            <excursion_more_info>
                <program>
                    Ден 1 : Полет София – Бергамо, Милано – Верона
                    Сборен пункт на летище София за полет до Милано два часа преди полета. 
                    Пристигаме на летище Бергамо и следва трансфер до Верона - един стар, приветлив, изтънчен, ведър и вечно влюбен град. Ще се изненадате от множеството забележителности, които „градът на Ромео и Жулиета“ ще ви разкрие за нула време. Трябва да кажем, че трагедията на Шекспир е само „куката“, която да ни закачи и потопи в средновековния дух на града. Веднъж спуснали се из улиците, по които Ромео се е гонел с Жулиета, бързо ще се убедим, че Верона е много повече от всичко, което сме си представяли. За деня е предвидена пешеходна обиколка. Вечерта се настаняваме в хотел в района на Верона. Нощувка.
                    Ден 2 : Верона – Венеция
                    Закусваме. За деня на Свети Валентин сме предвидили едно прекрасно изживяване – екскурзия до невероятната  Венеция / по желание и на доплащане/. Пристигаме на пристанище Пунта Сабиони, където ще се качим на корабче, за да стигнем до островния град. Венеция е град на канали, прелестни дворци и изящни мостове. Четири сезона в годината, в слънце и в дъжд, хора от всички раси и континенти се стичат тук. Хранят гълъбите на площад “Сан Марко”, изгубват се из уличките, купуват си сувенири, впускат се в романтично плаване по каналите, и си тръгват, отнасяйки Венеция в сърцето си. И ние ще направим точно това! Качваме се отново на корабче, за да се върнем на сушата. Вечерта отпътуваме към  хотела, намиращ се в района на Верона. Нощувка.
                    Ден 3 : Верона – Милано
                    Закусваме и се отправяме към централната част на Милано - италианската столица на модата и големите скандали. Най-пищната и най-голяма готическа катедрала в света е тук! Както и Миланската опера „Ла Скала“ и гигантския мрачен замък Сфорцеско. Ще видим всичко най-интересно и ще се разходим по най-престижната и луксозна модна улица в Италия. Надвечер, се отправяме към хотела ни в района на Милано. Нощувка.
                    Ден 4 : Полет Бергамо, Милано - София
                    Закуска(сух пакет), следва трансфер към летище Бергамо за полета ни до София. 
                </program>
                <more_excursions>
                    Туристическа програма във Венеция – 45 Евро;
					Туристическа програма в Милано – 20 евро.
                </more_excursions>
                <images>
                    <image>milano2.jpg</image>
		            <image>verona.jpg</image>
		            <image>venice.jpg</image>
                </images>       
            </excursion_more_info>
        </excursion>
    </excursions>
</excursions_catalog>

=== VeselaStoyanova/XMLProject/Project/Templates/transformation1.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE excursions_catalog SYSTEM "excursions_catalog.dtd">

<excursions_catalog>
    <excursions>
        <excursion>
            <basic_info>
                <code>ExcursionParis1</code>
                <category>Европа</category>
                <name>Парижка магия</name>
                <towns>Париж</towns>
                <price>1000 лева</price>
                <type>Самолет</type>
            </basic_info>
            <secondary_info>
                <route></route>
            </secondary_info> 
            <conditions>
                <enrollmentConditions></enrollmentConditions>
            </conditions>
    </excursion>
    </excursions>
</excursions_catalog>
